// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDMjWo9TRqlTLiA5wplXrJf2xRrUr1yws',
    appId: '1:718238661690:web:d275b4b63ca727947f8903',
    messagingSenderId: '718238661690',
    projectId: 'darbk-4ed01',
    authDomain: 'darbk-4ed01.firebaseapp.com',
    storageBucket: 'darbk-4ed01.firebasestorage.app',
    measurementId: 'G-6KTYLC34RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkMpSTFFpawzq5F61S0sFpSccl0YfDcc',
    appId: '1:718238661690:android:d2bef7b6a5b154417f8903',
    messagingSenderId: '718238661690',
    projectId: 'darbk-4ed01',
    storageBucket: 'darbk-4ed01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'OLD_KEY_REMOVED_SAFELY',
    appId: '1:718238661690:ios:3b87b634b691cb4b7f8903',
    messagingSenderId: '718238661690',
    projectId: 'darbk-4ed01',
    storageBucket: 'darbk-4ed01.firebasestorage.app',
    iosBundleId: 'com.DarbkApp.darbk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'OLD_KEY_REMOVED_SAFELY',
    appId: '1:718238661690:ios:3b87b634b691cb4b7f8903',
    messagingSenderId: '718238661690',
    projectId: 'darbk-4ed01',
    storageBucket: 'darbk-4ed01.firebasestorage.app',
    iosBundleId: 'com.DarbkApp.darbk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDMjWo9TRqlTLiA5wplXrJf2xRrUr1yws',
    appId: '1:718238661690:web:bb358d9c30be521c7f8903',
    messagingSenderId: '718238661690',
    projectId: 'darbk-4ed01',
    authDomain: 'darbk-4ed01.firebaseapp.com',
    storageBucket: 'darbk-4ed01.firebasestorage.app',
    measurementId: 'G-FF249P9RHY',
  );

}